create index classes_grade_level_idx on public.classes(grade_level_id);
create index classes_department_idx on public.classes(department_id) where department_id is not null;
create index profiles_institution_idx on public.profiles(institution_id);
create index homeroom_assignments_institution_idx on public.homeroom_assignments(institution_id);
create index homeroom_assignments_class_idx on public.homeroom_assignments(class_id);
create index homeroom_assignments_teacher_idx on public.homeroom_assignments(teacher_user_id);
create index student_enrollments_institution_idx on public.student_enrollments(institution_id);
create index student_enrollments_student_idx on public.student_enrollments(student_id);
create index student_enrollments_class_idx on public.student_enrollments(class_id);
create index rfid_credentials_student_idx on public.rfid_credentials(student_id);
create index rfid_credentials_registered_by_idx on public.rfid_credentials(registered_by) where registered_by is not null;
create index rfid_credentials_revoked_by_idx on public.rfid_credentials(revoked_by) where revoked_by is not null;
create index face_profiles_institution_idx on public.face_profiles(institution_id);
create index face_profiles_enrolled_by_idx on public.face_profiles(enrolled_by) where enrolled_by is not null;
create index attendance_schedule_rules_institution_idx on public.attendance_schedule_rules(institution_id);
create index attendance_schedule_rules_template_idx on public.attendance_schedule_rules(session_template_id);
create index attendance_schedule_rules_created_by_idx on public.attendance_schedule_rules(created_by) where created_by is not null;
create index attendance_occurrences_template_idx on public.attendance_session_occurrences(session_template_id);
create index attendance_occurrences_rule_idx on public.attendance_session_occurrences(source_schedule_rule_id) where source_schedule_rule_id is not null;
create index session_participants_student_idx on public.session_participants(student_id);
create index session_participants_enrollment_idx on public.session_participants(enrollment_id) where enrollment_id is not null;
create index device_events_occurrence_idx on public.device_events(occurrence_id) where occurrence_id is not null;
create index device_events_rfid_idx on public.device_events(rfid_credential_id) where rfid_credential_id is not null;
create index verification_attempts_device_idx on public.verification_attempts(device_id) where device_id is not null;
create index verification_attempts_event_idx on public.verification_attempts(device_event_id) where device_event_id is not null;
create index verification_attempts_occurrence_idx on public.verification_attempts(occurrence_id) where occurrence_id is not null;
create index verification_attempts_face_profile_idx on public.verification_attempts(face_profile_id) where face_profile_id is not null;
create index attendance_records_institution_idx on public.attendance_records(institution_id);
create index attendance_records_enrollment_idx on public.attendance_records(enrollment_id) where enrollment_id is not null;
create index attendance_records_device_idx on public.attendance_records(device_id) where device_id is not null;
create index attendance_records_verification_idx on public.attendance_records(verification_attempt_id) where verification_attempt_id is not null;
create index school_day_student_idx on public.school_day_attendance(student_id);
create index school_day_enrollment_idx on public.school_day_attendance(enrollment_id) where enrollment_id is not null;
create index school_day_arrival_record_idx on public.school_day_attendance(arrival_attendance_record_id) where arrival_attendance_record_id is not null;
create index school_day_departure_record_idx on public.school_day_attendance(departure_attendance_record_id) where departure_attendance_record_id is not null;
create index school_day_finalized_by_idx on public.school_day_attendance(finalized_by) where finalized_by is not null;
create index attendance_confirmations_institution_idx on public.attendance_confirmations(institution_id);
create index attendance_confirmations_actor_idx on public.attendance_confirmations(actor_user_id);
create index audit_logs_institution_idx on public.audit_logs(institution_id) where institution_id is not null;
